export const data = [
    {
        id:1,
        name:"Dashboard",
        path:"/",
    },
    {
        id:2,
        name:"Accounts",
        path:"/accounts",
    },
    {
        id:3,
        name:"Audits",
        path:"/audits",
    },
    {
        id:4,
        name:"Notifications",
        path:"/notifications",
    },
    {
        id:5,
        name:"Profile",
        path:"/profile",
    },
    {
        id:6,
        name:"Administration",
        path:"/administration",
    },
]